//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObliqueStrategies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strategies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strategies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ObliqueStrategies.Strategies", typeof(Strategies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///  &lt;appSettings&gt;
        ///    &lt;add key=&quot;autoshow&quot; value=&quot;0&quot;/&gt;
        ///    &lt;add key=&quot;showonstart&quot; value=&quot;true&quot;/&gt;
        ///  &lt;/appSettings&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandon normal instruments
        ///Accept advice
        ///Accretion
        ///A line has two sides
        ///Allow an easement
        ///Are there sections? Consider transitions
        ///Ask people to work against their better judgement
        ///Ask your body
        ///Assemble some of the instruments in a group and treat the group
        ///Balance the consistency principle with the inconsistency principle
        ///Be dirty
        ///Breathe more deeply
        ///Bridges -build -burn
        ///Cascades
        ///Change instrument roles
        ///Change nothing and continue with immaculate consistency
        ///Children&apos;s voices -speaking -si [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Edition1 {
            get {
                return ResourceManager.GetString("Edition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandon normal instruments
        ///Accept advice
        ///Accretion
        ///A line has two sides
        ///Allow an easement
        ///Always first steps
        ///Always give yourself credit for having more than personality
        ///Are there sections? Consider transitions
        ///Ask people to work against their better judgement
        ///Ask your body
        ///Assemble some of the instruments in a group and treat the group
        ///A very small object -Its centre
        ///Balance the consistency principle with the inconsistency principle
        ///Be dirty
        ///Be extravagant
        ///Breathe more deeply
        ///Bridges -build [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Edition2 {
            get {
                return ResourceManager.GetString("Edition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandon normal instruments
        ///Accept advice
        ///Accretion
        ///A line has two sides
        ///Allow an easement
        ///Always first steps
        ///Are there sections? Consider transitions
        ///Ask people to work against their better judgement
        ///Ask your body
        ///Assemble some of the elements in a group and treat the group
        ///Balance the consistency principle with the inconsistency principle
        ///Be dirty
        ///Be extravagant
        ///Be less critical more often
        ///Breathe more deeply
        ///Bridges -build -burn
        ///Cascades
        ///Change instrument roles
        ///Change nothing and continu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Edition3 {
            get {
                return ResourceManager.GetString("Edition3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandon desire
        ///Abandon normal instructions
        ///Accept advice
        ///Adding on
        ///A line has two sides
        ///Always the first steps
        ///Ask people to work against their better judgement
        ///Ask your body
        ///Be dirty
        ///Be extravagant
        ///Be less critical
        ///Breathe more deeply
        ///Bridges -build -burn
        ///Change ambiguities to specifics
        ///Change nothing and continue consistently
        ///Change specifics to ambiguities
        ///Consider transitions
        ///Courage!
        ///Cut a vital connection
        ///Decorate, decorate
        ///Destroy nothing; Destroy the most important thing
        ///Discard [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Edition4 {
            get {
                return ResourceManager.GetString("Edition4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandon normal instruments
        ///Accept advice
        ///Accretion
        ///Allow an easement
        ///Always first steps
        ///Are there sections? Consider transitions
        ///Ask people to work against their better judgement
        ///Ask your body
        ///Be dirty
        ///Be extravagant
        ///Be less critical more often
        ///Breathe more deeply
        ///Change nothing and continue with immaculate consistency
        ///Courage!
        ///Cut a vital connection
        ///Decorate, decorate
        ///Define an area as &apos;safe&apos; and use it as an anchor
        ///Destroy -nothing -the most important thing
        ///Discard an axiom
        ///Disciplined  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Edition5 {
            get {
                return ResourceManager.GetString("Edition5", resourceCulture);
            }
        }
    }
}
